# config_gpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: europe-north2-docker.pkg.dev/mlops-483519/ar-docker-1/train-image:latest